### ISSUE TITLE
Step failure no such file or directory

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/steps-change-workdir#3]
Hi,
I am using the step to change the working directory, i have the property "Create path if doesn't exist?" set to true, but for some reason its not working. 
Here is the log:

+------------------------------------------------------------------------------+
| (0) change-workdir@1.0.1                                                     |
+------------------------------------------------------------------------------+
| id: change-workdir                                                           |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-06-27T02:00:22-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
ERRO[02:00:23] Step (change-workdir@1.0.1) failed, error: chdir /Users/vagrant/git_sit_cal: no such file or directory 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | change-workdir@1.0.1 (exit code: 0)                          | 3.1 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-change-workdir/issues     |
| Source: https://github.com/bitrise-io/steps-change-workdir                   |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Could you please attach the bitrise.yml, or just this step's config from it?

**Comment by Reedyuk** [comment]
Can i do this privately? i don’t want some items in it being exposed publicly.

**Comment by viktorbenei** [comment]
Sure, send it in email or through the onsite chat

**Comment by viktorbenei** [comment]
So the issue seems to be that you overwrite the `BITRISE_SOURCE_DIR` environment variable.

That env var is used for determining the "working directory". If you just set it to a path then that path is expected to exist, or else the steps might fail with the error you reported.

The best way to handle changing the working directory is to use this step. This step can create the directory for you and will set the `BITRISE_SOURCE_DIR` env too, you should not set the environment variable directly, unless you're sure that the directory exists.

I'll close this issue, if you'd have any question / this wouldn't solve the issue feel free to comment and we'll reopen it.

And of course, thanks for reporting the issue!!
